#!/usr/bin/env bash
# configuring web-02 to be identical to web-02
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
echo 'Hello World!' > /var/www/html/index.nginx-debian.htm
echo 'Hello World!' > /var/www/html/index.htm
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm index.nginx-debian.htm;
    server_name _;
    add_header X-Served-By \$hostname;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
