#!/usr/bin/env bash
# Installing UFW and blocking traffic
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
