#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/
pkill apache2
sudo -u nginx service nginx restart
