#!/usr/bin/env bash
# Run nginx as nginx user and config nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/
pkill apache2default
sudo -u nginx service nginx restart
